### ISSUE TITLE
128 channels are not enough

### ISSUE THREAD

**Issue by bkchr** [aep/devguard#2]
Based on the assumption that a bearer and a peer are running for the entire time the universe is alive, 128 channels are not enough. You are freeing the channels in your HashMap, but you don't inform the other side that the channel is closed. So you will go out of channels.

**Comment by aep** [comment]
Channels are closed inside the crypto to prevent external analysis. (See the packet header description in readme.md or noise.rs). 

I want to go even further and rotate the channels after some time to make it impossible to distinguish an inner channel from a control channel. 

Since rekeying  isn't  implemented yet, every channel simply terminates after u16 max packets.

Let me know if that clarifies your question

**Comment by bkchr** [comment]
I thought that the channel ids are not encrypted? Does that attacker does not see that the channel is not used anymore, because he does not see the id anymore?

And could you explain what are control and inner channels?

If a channel terminates after u16 packets and you still communicate, it just opens a new channel for you?

And why does you want to rotate the channels? To prevent making assumptions where the data is goes?

**Comment by aep** [comment]
indeed they are not encrypted. this is why i want to rotate them to make tracking them harder.

A control channel is the one used to exchange messages with the bearer.  As far as i know, knowing the control channel does not give an attacker any advantages. We could easily hide it inside the crypto later, if we think it's a problem, but i don't want to touch any of the protocol right now before we have udp.

**Comment by aep** [comment]
closing this, since we're no longer using channels
